### ISSUE TITLE
Publish a new release once PRs are merged

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#103]
We should publish a new release once the open PRs are merged.

Apart from publishing to the Chrome and Mozilla stores, it might be nice to publish bundled releases for the different browsers here on GitHub as well so people can download and install them if they prefer this method:
https://github.com/bitcrowd/tickety-tick/releases

The bundles can be built using:

```shell
yarn build:chrome
yarn build:firefox-local
yarn build:safari
```

**Comment by klappradla** [comment]
Published and released versions `2.0.0` and `2.0.1` (for Chrome and Firefox). Will update some more screenshots and then close this I guess.
