### ISSUE TITLE
Temporarily load Firefox addon

### ISSUE THREAD

**Issue by klappradla** [bitcrowd/tickety-tick#106]
I just realized it's not possible to temporarily load the Firefox build build via

    yarn build:firefox

The popup won't load any content:

<img width="1792" alt="screen shot 2018-10-26 at 12 25 01" src="https://user-images.githubusercontent.com/3491815/47561120-b3940700-d91a-11e8-82f1-d74a41f448e0.png">

This is also reported when submitting a new version to the Firefox addons place:

<img width="1792" alt="screen shot 2018-10-26 at 12 29 52" src="https://user-images.githubusercontent.com/3491815/47561187-da523d80-d91a-11e8-9722-37ddb03fd7ad.png">

They essentially report these warnings:

```
"storage.sync" can cause issues when loaded temporarily
Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.
options.js line 6 column 1237

"storage.local" can cause issues when loaded temporarily
Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.
options.js line 6 column 1258

Unsafe assignment to innerHTML
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
options.js line 22 column 35324

Unsafe assignment to innerHTML
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
options.js line 22 column 35347

"storage.sync" can cause issues when loaded temporarily
Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.
popup.js line 6 column 1237

"storage.local" can cause issues when loaded temporarily
Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.
popup.js line 6 column 1258

Unsafe assignment to innerHTML
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
popup.js line 22 column 35324

Unsafe assignment to innerHTML
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
popup.js line 22 column 35347
```

I'm not sure if that's actually a problem, since one can still use

    yarn build:firefox-local

to produce a build usable as a tmp add on.

Just wanted to report this and that Firefox itself regards it as a problem as well 😉

**Comment by pmeinhardt** [comment]
Hey @klappradla, for building and loading a local development version of the Firefox version of Tickety-Tick, there are two separate `npm` scripts that produce different output compared to a production build:

* [`yarn build:firefox-local`](https://github.com/bitcrowd/tickety-tick/blob/dd58313545dbd6261e14bd7a400046ebf6258813/package.json#L14)
* [`yarn open:firefox-local`](https://github.com/bitcrowd/tickety-tick/blob/dd58313545dbd6261e14bd7a400046ebf6258813/package.json#L21)

See this part in the README: https://github.com/bitcrowd/tickety-tick#developing-tickety-tick.

Also, see this issue/comment here for a little bit of background (tldr: the local build requires an "addon-id" to be inserted into the manifest on build whereas the submitted build should not contain one).

I'm not sure whether this solves your issue of loading the extension locally?

---

As for the warnings ⚠️ on the submitted version: Let's go through them and address these issues if possible/necessary 🙂
