### ISSUE TITLE
Additional #-character when directly viewing an issue on pivotal.

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#11]
![image](https://cloud.githubusercontent.com/assets/239398/15352816/559e5274-1ce6-11e6-8b41-cc703aa895b5.png)

When you use the direct URL to an issue on pivotal, instead of viewing all issue in the issue list, tickety-tick produces an extra '#'.

**Comment by pmeinhardt** [comment]
Could you check whether this issue still exists in the new version (1.0.1) once released? 😃

**Comment by bitboxer** [comment]
I can confirm that this is is fixed now. Closing the ticket.

**Comment by pmeinhardt** [comment]
Yippieh.
