### ISSUE TITLE
Doesn't work with the new version of ora.pm

### ISSUE THREAD

**Issue by nickgnd** [bitcrowd/tickety-tick#116]
Version 2 of `ora.pm` is still in [beta](https://ora.pm/blog/ora-2-beta), don't know when will be released.

**Comment by pmeinhardt** [comment]
Is this still an issue @nickgnd? Otherwise, it'd be great to close this issue. Thank you 💚

**Comment by nickgnd** [comment]
@pmeinhardt I have just checked. It is working partially. The commit message is extracted correctly, but not the branch name which reports all the issue types in the prefix 😞 : 

`chore-bug-chore-story-feature-docs-epic-investigation/customerName123-ticket-title`

**Comment by pmeinhardt** [comment]
Okay, so it somewhat works 😂 Let's keep this open then. Just wanted to check what the current state is. Thanks a lot @nickgnd 💚
