### ISSUE TITLE
Bugs/Chores are not recognized as such in JIRA/Atlassian

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#12]
Somehow in JIRA every generated branch seems to start with `feature/ ` no matter if its a feature, a bug or a chore ticket. 
(can be reproduced in Chrome and Firefox)

**Comment by bitboxer** [comment]
This still happens in 1.0.1

**Comment by pmeinhardt** [comment]
Done, via #32

**Comment by pmeinhardt** [comment]
Nice work @weiland
