### ISSUE TITLE
Configurable branch name prefix "feature/"

### ISSUE THREAD

**Issue by fabienchn** [bitcrowd/tickety-tick#134]
Would it be possible to make the `feature/` prefix (for the branch name) configurable ?
In my case I would like to have no prefix at all.
But it would probably also be nice to be able to choose another string instead of `feature`.

**Comment by klappradla** [comment]
Hey @fabienchn 👋 

Thanx for reaching out!

Yes, it would and actually **already is** possible to configure (also fully remove) the prefix! You can do this in the [Advance Configurations](https://github.com/bitcrowd/tickety-tick#advanced-configuration) (the README will point you to where you can find them in the browser you're using).
In Firefox, they for example look like this:
![screenshot 2019-02-11 at 12 02 43](https://user-images.githubusercontent.com/3491815/52559203-f825ae80-2df4-11e9-91d0-7909f63dacfe.png)

For your particular case, have a look at the **Branch Name Format** field. The help text already dives a hint for what you could need:
```
{type}/{id | slugify}-{title | slugify}
```

You could for instance just ditch the `type`:
```
{id | slugify}-{title | slugify}
```

You can use various helper functions to get things into the desired format (they are listed on the configuration page directly).

Does that solve your problem? Feel free to reopen if there's still something missing ✌️

**Comment by fabienchn** [comment]
Hi @klappradla that's exactly what I was looking for, awesome thank you !
