### ISSUE TITLE
Extract jQuery/remove it

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#14]
Mozilla review sent the following message:

> Hello,
>
> A reviewer requested further information from you regarding version 1.0.0 of your add-on tickety-tick.
>
> Baris Derin wrote:
>
> It seems background.js is jquery file. Save jquery file as separate file please.
>
> We require all add-ons to use unmodified release versions from official jQeury site.
>
> Thank you.

**Comment by pmeinhardt** [comment]
May not be needed depending on the outcome of #17

**Comment by bitboxer** [comment]
Nope, this is a separate request by the reviewer. You saldy need to do this.

**Comment by pmeinhardt** [comment]
I wonder what would happen if we included Zepto instead of jQuery 😆

**Comment by bitboxer** [comment]
And the reviewer never mentioned react or some of the other dependencies 🎯 . But we do as they wish to get this released quickly.

**Comment by pmeinhardt** [comment]
Yep, was just kidding. Working on it

**Comment by pmeinhardt** [comment]
Hey @bitboxer, extracted jQuery which is now copied into the extension directory from the npm directory (`./node_modules/jquery/dist/jquery.js`). I assign `window.$$$ = $.noConflict(true);` in the `content.js` script now that jQuery is global, to avoid clashes with existing jQuery instances in the content page. The Safari code is also updated accordingly.

Can you have another look at it? Maybe prepare another release for submitting it to Mozilla?

Thanks.

PS: Also, I found this: https://developer.mozilla.org/en-US/Add-ons/Extension_etiquette
