### ISSUE TITLE
Tickets with a dash lead to discarded ticket-ids

### ISSUE THREAD

**Issue by acid** [bitcrowd/tickety-tick#152]
Hello,

at first thank you for this great tool! I don't want to miss it in my daily work. At my workplace we have Jira Tickets like "ABC-1234 cool thing" sadly this leads to output like this `git checkout -b 'feature/-cool-thing' && git commit --allow-empty -m '[#] cool thing'` which is kinda annoying.

How can we improve this? If you guide me in which part the parsing is done I'm happy to create a PR for the fix on my own.

**Comment by klappradla** [comment]
Hm, have you double checked if you can get around this via. [configuring patterns](https://github.com/bitcrowd/tickety-tick#advanced-configuration) for branchnames yourself?

**Comment by acid** [comment]
@klappradla thanks for the quick feedback! I tried that but the problem seems to be that id is empty or not in a usable way.

**Comment by andreasknoepfle** [comment]
I think this happens due to JIRA pages not parsed properly currently (I think you are using JIRA at your company no? ;) ) I have seen similar issues with other JIRA instances.

We made a couple of improvements here lately: 

See #137 for example. 
I am not sure though if those changes were already released.  @klappradla @paul can maybe give insights here?

**Comment by andreasknoepfle** [comment]
Just checked, I think the PR was not yet released in a new version.

**Comment by acid** [comment]
@andreasknoepfle ok, please let me know when it was released and I'll let you know here if it fixed this issue for me :)

And you're right, we're using Jira here, sorry for missing this information!

**Comment by andreasknoepfle** [comment]
Hey @acid. We released the new 3.0.0 version of tickety-tick. Can you verify if the problems are gone now :)

**Comment by acid** [comment]
@andreasknoepfle awesome, that fixed it! Thank you very much 💜
