### ISSUE TITLE
Github tickety-tick issues seem to not work anymore

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#154]
<img width="1331" alt="Screenshot 2019-04-12 at 11 21 39" src="https://user-images.githubusercontent.com/239398/56026777-2d774b80-5d15-11e9-9ff7-5bc616cbce47.png">
Maybe github changed their markup.

**Comment by bitboxer** [comment]
Do you plan to fix this in the near future?

**Comment by bitboxer** [comment]
Since nobody answered I used a bit of this nice day to sit in a hammok and write the fix for this. Hope you like it  :wave:

**Comment by bitboxer** [comment]
![homer in a hammock](https://media.giphy.com/media/3orieP77Lhw1S9pEgU/source.gif)

**Comment by bitboxer** [comment]
so when is the next release scheduled  :rofl: ?

**Comment by pmeinhardt** [comment]
It'll probably ship later today @bitboxer ⛵️

**Comment by bitboxer** [comment]
:tada: Thank you! :bowing_man:

**Comment by pmeinhardt** [comment]
The new release is now available on the Chrome and Firefox stores @bitboxer 🕺 
Shout-out to @andreasknoepfle for publishing them 💚
