### ISSUE TITLE
Add a screencast to the readme?

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#159]
Should we add a short screencast to the README to demo how Tickety-Tick works and give people coming across this repo a better idea about it?

**Comment by klappradla** [comment]
💥 awesome advertising idea!

Let's schedule this for our next hacknight / lunchhacking.

**Comment by klappradla** [comment]
Another person requested this: https://github.com/syntax-tree/mdast/pull/40#issuecomment-1047578714 📌

**Comment by klappradla** [comment]
Plan of attack: run a script to show the core features.

Record using `kap.app` (it has a plugin to show keys pressed). We may need to edit the result to remove gaps.

**Comment by klappradla** [comment]
Made a tiny attempt 🍿 

![tt-demo-small](https://user-images.githubusercontent.com/3491815/165542748-badc6687-2255-4a98-9d0e-458e8043fbbd.gif)
