### ISSUE TITLE
Unable to copy default value in settings

### ISSUE THREAD

**Issue by maltoe** [bitcrowd/tickety-tick#165]
Hello friends,

just a minor annoyance I just noticed, not even sure this is TT's fault or just chrome code:

When I try to change a setting in the Chrome extension settings, say the formatter's `branch` setting, I can't copy the existing value as it is just a placeholder in the input.

![ticketytick_cant_copy](https://user-images.githubusercontent.com/96114/58692536-1822b300-838f-11e9-8cf5-9bd02ffaa583.gif)

❤️ 
malte

**Comment by pmeinhardt** [comment]
Ah, indeed. I totally see why that's slightly frustrating @maltoe 💚 Great screencast 😄 
The default is just shown as a standard browser [input placeholder](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Labels_and_placeholders) which is not selectable.

I guess the alternative would be to set the input value itself to the default value on blur if the field is empty. Would that be the behavior you'd prefer @maltoe?

Also pinging @lwassermann here who might have more input?

**Comment by maltoe** [comment]
@pmeinhardt Or just prefill the field with the default, and don't persist it if it hasn't been changed?

**Comment by andreasknoepfle** [comment]
We could also prefill it and have a reset button or something like this, to go to be able to go to the default again.

**Comment by pmeinhardt** [comment]
Fixed by #170.
