### ISSUE TITLE
Unintended breaking change on Trello ticket IDs

### ISSUE THREAD

**Issue by klappradla** [bitcrowd/tickety-tick#167]
Trello's ticket URLs look approximately like this:

    https://trello.com/c/wkvhWD7u/615-5-remove-break-screens

Versions < 3.0 of TicketyTick used `615-5` as the main reference / ID for the ticket in both, the commit message as well as the branch name.

From the current (3.0) version on, TicketyTick uses the anchor tag as main refence / ID. So branch names look like this:

    feature/wkvhwd7u-5-remove-break-screens

And commit messages / PR references like this:

    [#wkvhWD7u] (5) Remove break screens

This may not be a big problem, but it's a breaking change that we did not document in the changelog / the relase notes 🤷‍♂ What do you think?

**Comment by tessi** [comment]
I used it on a trello project for a week now. It makes life a little harder when finding old branches (they are not sorted anymore by ticket-creation-date which makes it harder to scan them).

Apart from that I personally don't care. The question is, if we think clients don't like this change (since this text appears in bills/joblogs)

**Comment by tessi** [comment]
cc @xhr15 ☝️

**Comment by pmeinhardt** [comment]
Good catch @klappradla. The motivation for this change was that the `shortId` is not actually a good identifier for tickets according to the Trello API documentation. More details here: https://github.com/bitcrowd/tickety-tick/pull/138#discussion_r267130364

Would it be okay to update the release notes?

**Comment by klappradla** [comment]
Thanks for the link @pmeinhardt 🙏 Now I event remember the conversation about it!

Guess it's fine to just quickly mention in in the release notes _(also this issue wasn't about a "bug")_.

**Comment by pmeinhardt** [comment]
I've updated the release notes:

![updated release notes](https://user-images.githubusercontent.com/706519/58851846-cb3b2700-8683-11e9-8912-e31c9586e1dd.png)

Please re-open if you're missing anything!

✌️

**Comment by klappradla** [comment]
@pmeinhardt 👑
