### ISSUE TITLE
Create source zip for mozilla

### ISSUE THREAD

**Issue by bitboxer** [bitcrowd/tickety-tick#17]
Mozilla needs a source zip file that I upload to show them that this code is okay, even if it is minified 😉

**Comment by pmeinhardt** [comment]
Can you just use one of these?

1. https://github.com/bitcrowd/tickety-tick/archive/master.zip, or
2. https://github.com/bitcrowd/tickety-tick/releases

**Comment by bitboxer** [comment]
Ah, yes. Thanks!
