### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#178]
We could make it easier to release tickety tick by automating it a bit better. 
- [x] Add a task for zipping the safari extension
- [x] Add a script to draft a new release and upload the bundles to github (maybe for running in CI on new tags)

Optional: 
- [x] Use the commit history/changelog to create release descriptions

**Comment by klappradla** [comment]
Some work-in-progress notes on that:

Following up on a discussion I had with @pmeinhardt on https://github.com/bitcrowd/tickety-tick/issues/212, I quickly tried out [`np`](https://github.com/sindresorhus/np) introduced in #184 to automatically create Github releases. It works perfectly fine for that, but as expected does not support adding downloadable release artifacts 😞  _(people already wanted to use it for [uploading extensions](https://github.com/sindresorhus/np/issues/92))_

What works pretty neat is this Github Action: https://github.com/actions/upload-release-asset. The [example workflow](https://github.com/actions/create-release#example-workflow---create-a-release) essentially combines two actions (one for creating the release and one for adding a downloadable artifact to the new release).

We'll probably need to combine a few tools. Some more are:
- [chrome-webstore-upload-cli](https://github.com/DrewML/chrome-webstore-upload-cli)
- [web-ext-sign](https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-sign)

Here is an [example workflow](https://github.com/npmhub/npmhub/blob/955beed238d85fe41a60c04d01dc99dfe85bd6c6/.github/workflows/deploy-tag.yml) from another extension project which does the two uploads.

**Comment by klappradla** [comment]
Done as a semi automated, Capistrano-like flow 🐘

**Comment by metaqer** [comment]
hello

**Comment by metaqer** [comment]
hello
