### ISSUE TITLE
Per Repo Templates?

### ISSUE THREAD

**Issue by bitboxer** [bitcrowd/tickety-tick#185]
I now run into the issue that I have 3 customers with different needs regarding the git commit templates. It would be awesome if it is possible to add repo specific templates.

What do you think? Since you are an agency with several customers, you might run into this, too :wink: ?

**Comment by pmeinhardt** [comment]
Sounds like a lot of work. We'd probably have to establish a concept of "profiles" that you can edit in the settings and quickly switch between from the extension popup.

I personally don't switch projects often enough that this would be "a thing" for me at the moment. Also, most client projects we enter don't even have a branch/commit convention to start with, so they're happy just adopting our defaults. 🤷‍♂ 

Feel free to submit a PR though if you care enough @bitboxer ✌️

**Comment by pmeinhardt** [comment]
Maybe you could even use a browser-profile per customer/client to manage different extension settings?

**Comment by klappradla** [comment]
Did you come up with a solution for your workflow @bitboxer?

> use a browser-profile per customer/client to manage different extension settings?

That's probably worth a try and closest to having separate "desks" for each client / project?

I guess nobody here has strong enough needs to actually get into the topic themselves. I'll close this for now, feel free to re-open if the problem keeps bugging you and you maybe have some suggestions on how to fix it? 🦄

**Comment by bitboxer** [comment]
I never came up with one that didn't involve me to hand tweak the branch names/commit messages. Currently, I am only working for one client and that problem is gone.
