### ISSUE TITLE
Buttons get displayed off screen when ticket title is too long and can't be broken

### ISSUE THREAD

**Issue by maltoe** [bitcrowd/tickety-tick#194]
When tickets have really long names that can't be line-broken (e.g., filesystem paths, URLs), the buttons are displayed off-screen.

<img width="320" alt="Screenshot 2019-11-11 at 14 12 18" src="https://user-images.githubusercontent.com/96114/68589920-8070d700-048d-11ea-93cb-35655e97d604.png">

Workaround is to click into the tickety-tick dialog and hit `<Tab>` once, but it would be nice if the buttons would always show below the ticket title for long names.

💚

**Comment by pmeinhardt** [comment]
Resolved in v4.0.0 (to be released soon) with the new compact design. See #221.
