### ISSUE TITLE
Install from file not working for Firefox

### ISSUE THREAD

**Issue by klappradla** [bitcrowd/tickety-tick#212]
I think™ this may actually be related to what I reported earlier in #106 🙈 : it's currently not possible to install the Firefox build as a "permanent" add-on "from file" as described in [the README](https://github.com/bitcrowd/tickety-tick#firefox).

One cannot select the `manifest.json` file for this. And trying to use the "bundle" zip file build for the submitting it to the Firefox add-ons collection also yields an error:
<img width="392" alt="Screenshot 2020-02-28 at 00 06 37" src="https://user-images.githubusercontent.com/3491815/75495248-5b618f00-59be-11ea-9c7c-ab2c998bc568.png">

It would be super helpful for the developers here ab bitcrowd to be able to run a "beta" version locally.

We should try to update our `webext` config to produce a build we can install permanently in my opinion.

**Comment by pmeinhardt** [comment]
For some more pointers: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by pmeinhardt** [comment]
It very much sounds like it is no longer possible to install self-built, unsigned extensions in "Release" and "Beta" Firefox.

https://wiki.mozilla.org/Add-ons/Extension_Signing

> What are my options if I want to install unsigned extensions in Firefox?
>
> The Nightly and Developer Edition versions of Firefox have a preference to disable signature enforcement. There are also be special unbranded versions of Release and Beta that have this preference, so that add-on developers can work on their add-ons without having to sign every build. To disable signature checks, you will need to set the `xpinstall.signatures.required` preference to "false".
> - type `about:config` into the URL bar in Firefox
> - in the Search box type `xpinstall.signatures.required`
> - double-click the preference, or right-click and selected "Toggle", to set it to `false`.

It sounds like we have the option to publish "beta" releases of Tickety-Tick:

> What about Beta versions on AMO? Will they be reviewed and signed?
>
> Yes. Beta versions will be treated like non-AMO add-ons. They will be automatically validated and signed if they pass validation.

Or maybe there's some way of self-signing them (requires access to Mozilla API):
https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-sign

This is somewhat annoying 🤔

**Comment by tessi** [comment]
Alternatively, we could locally use a dev eition of firefox 🤔

**Comment by klappradla** [comment]
Thanks for digging into this @pmeinhardt 🙏 (I simply wanted to report it yesterday - did not look into the details yet).

Running the local "bundled" build in Firefox Nightly works like charm ❤️ 

We'd probably have to document the way to get there though... Plus a small downside: the Nightly build often has some super weird 🐛 🐝 which could impact working with the "beta" version of TicketyTick on a daily basis.

**Comment by pmeinhardt** [comment]
> Alternatively, we could locally use a dev eition of firefox 🤔

I guess one underlying question is whether we want to allow people to just use their normal browser (and browser setup) when using a custom-built version of Tickety-Tick?

![dev edition](https://user-images.githubusercontent.com/706519/75527569-d781c400-5a0a-11ea-9e3d-dcc1ddd8b10b.png)

I personally find it quite inconvenient that you can no longer easily install extensions built from source. 😢 For just test-driving a built extension on an artificial example scenario, using Nightly/Dev-Edition is not a problem, but for those that want to build their own and not publish it?

🤷‍♂

**Comment by klappradla** [comment]
🙈 I can install it, but I cannot use it with Jira 😹 

Tickety-Tick revision: 12ba96ad6a933d6c90d8575c883b4377b18e5d15

```
Not Found
    at constructor (webpack:///node_modules/ky/index.js:120:2)
    at response.clone (webpack:///node_modules/ky/index.js:274:10)
    at _retry (webpack:///node_modules/ky/index.js:347:16)
    at TypeError (webpack:///node_modules/ky/index.js:295:42)
    at Ky (webpack:///node_modules/ky/index.js:452:35)
    at scan (webpack:///src/common/adapters/jira.js:58:30)
    at attempt (webpack:///src/common/search.js:10:26)
    at search (webpack:///src/common/search.js:28:47)
    at search (webpack:///src/common/search.js:28:25)
    at browser.runtime.onMessage.addListener( (webpack:///src/web-extension/content.js:8:13)
```

**Comment by pmeinhardt** [comment]
Sounds like we might have accidentally broken something when upgrading `ky` 🤔 

I'll take a look 🔍  https://github.com/sindresorhus/ky/releases

**Comment by pmeinhardt** [comment]
Or maybe, while you're at it @klappradla, you could quickly try downgrading `ky` back to `^0.14.0`, rebuild and try it out?

**Comment by klappradla** [comment]
Yes, already tried out going back to the version before the updates (14). Same problem.

**Comment by pmeinhardt** [comment]
> 🙈 I can install it, but I cannot use it with Jira 😹

Let's tackle this together with the Jira issue in #195?
It is not really related to this issue I think.
I'll link your comment there @klappradla. ✌️

**Comment by pmeinhardt** [comment]
I think we've answered the question about installing a custom-built version in Firefox here, so I'll close the issue. Feel free to re-open if I've overlooked something. 🙂

**Comment by klappradla** [comment]
We sorta did, but I'm not satisfied with the answer yet 😉 

I guess we should at least update the docs for how to install a custom build. In addition to that, I'd suggest we explore possible alternatives for using "beta" versions of the extension. I could think of:
1. signing our local build
1. actually releasing "beta" versions
1. marking the local build as somehow different to the actual extension

Ad 3: it's a bit of a hassle to switch out the extension in a nightly build _(probably regardless of Chrome or Firefox)_ if one also uses some synchronization for browser settings across machines. Ideally, one could just install **two** versions of TicketyTick and just toggle which one is enabled.

**Comment by pmeinhardt** [comment]
@klappradla, I just stumbled across this: https://extensionworkshop.com/documentation/publish/

Sounds like there are might be different options for us to distribute "beta" versions.

One of them, registering a separate "Tickety-Tick (Latest)" on the Chrome + Mozilla stores, maybe even automatically pushing new versions for this in CI from `master.

Not sure whether the "sideloading" which the site talks about really works. It seems like that's what we've tried before. However, it sounds like it's actually possible to sign the extension, using `web-ext` for instance, to get around the "temporary install" restriction.

**Comment by klappradla** [comment]
I tried out [`web-ext-sign`](https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-sign) which is pretty neat and probably already sufficient for what we need 💜 

It essentially does two things:
1. Upload an `unlisted` beta version of the extension to `addons.mozilla.org`
  The version is not available for public download, but bitcrowd developers with credentials could do a one-click install from there.
1. Generate a `tickety-tick-whatever.xpi` file
  This allows installing the add on "manually" from file in Firefox

Not 100% sure how to proceed from here... I could add `dotenv` to the project, commit my changes to the `package.json` including the `sign` command and have a `.env` file with the respective credentials in our shared password manager.

We could also think about storing the credentials on CI and instead run the signing there (maybe on a specific `beta` branch) and make the artifact available from there 🤔

**Comment by pmeinhardt** [comment]
That's awesome @klappradla. Thank you so much for digging into this. 💖 

I like the idea of automatically pushing beta builds from CI. It sounds like a convenient solution. Maybe instead of using a `beta` branch, we might want to use `x.x.x-beta` tags? This way it might be easier to try out things on different branches without messing up/force-pushing a `beta` branch because of conflicting changes.
