### ISSUE TITLE
Config subject length

### ISSUE THREAD

**Issue by tiagotex** [bitcrowd/tickety-tick#213]
We updated from 3.1.0 to 3.2.0 and now the commit message returned is:

```
Wrap commit subject lines with more than 50…

…characters and insert one blank line before the remaining subject text.
```

In 3.1.0 it was:
```
Wrap commit subject lines with more than 50 characters and insert one blank line before the remaining subject text
```

In our use case we don't want to break the commit messages at 50 characters, because we use 13 characters for the ticket number and this would not give us enough space to have good subjects descriptions.

https://github.com/bitcrowd/tickety-tick/blob/master/src/common/format/pretty-print.js#L5

Would you consider adding the option to change the subject and body width in the advanced configurations?

I'm available to implement that change if you would like.

Thank you for the good work and the new version release 💚

**Comment by pmeinhardt** [comment]
Hey @tiagotex 👋🙂

There is an option to toggle pretty-printing in the extension preferences (which we decided to enable by default).

![screenshot](https://user-images.githubusercontent.com/706519/75828819-9e4baa00-5da4-11ea-933e-34239623b75c.png)

Disabling it should prevent breaking subject lines longer than 50 characters, although it will also mean, the commit body is not formatted to a width of 72 characters.

Does this cover your case?

**Comment by tiagotex** [comment]
Yeah, that is enough for us. Thank you for the fast response 😊
