### ISSUE TITLE
Error Message when opening with firefox

### ISSUE THREAD

**Issue by kajatiger** [bitcrowd/tickety-tick#214]
I am getting this error message when using tickety-tick as a firefox addon with jira:
Tickety-Tick revision: 9cf09759676404542de0980f6524dd2996d6f08e 

```
Not Found
    at constructor (webpack:///node_modules/ky/index.js:137:2)
    at response.clone (webpack:///node_modules/ky/index.js:329:10)
```
<img width="363" alt="Bildschirmfoto 2020-03-09 um 11 01 50" src="https://user-images.githubusercontent.com/15628617/76202907-ef6cfb00-61f5-11ea-80f4-5a2d006de60a.png">

And these are my configurations. I wonder if that has something to do with the error?
<img width="699" alt="Bildschirmfoto 2020-03-09 um 11 02 16" src="https://user-images.githubusercontent.com/15628617/76203025-35c25a00-61f6-11ea-9a8e-d1a736239bb2.png">

**Comment by klappradla** [comment]
Thanks for reporting @kajatiger 🦄 

This may be related to the problem described in https://github.com/bitcrowd/tickety-tick/issues/212#issuecomment-592428436 _(and therefore related to some dependency updates we did 🤔 ...)_

Although it looks like a different problem, just to ensure this is not a duplicate of https://github.com/bitcrowd/tickety-tick/issues/195, do you by chance recall in which "view" (sprint, backlog, etc.) the problem occurred and whether it was on a so called _"next gen"_ Jira project?

**Comment by kajatiger** [comment]
I don't think this relates to either of these two mentioned problems, because 
1. I don't have any problems installing the addon with firefox and
2. It correctly matches the ticket with the PR, once I manually created the branch, commit & PR with the given naming convention including the ticket ID
3. The error occures no matter what kind of Jira ticket I am viewing (in my case current sprint, backlog ticket). I have no clue about the next gen thing though.

The only other idea I have would be that add blocker or ghostery or lightbeam is interfering with the tickety-tick addon...

**Comment by tessi** [comment]
Thanks @kajatiger for reporting this issue 💚 . Sadly, I have no obvious idea what exactly fails for you, but I noticed that the error message is very unhelpful. Maybe we should provide better errors ins tickety-tick in case of HTTP errors (I see that it comes from `ky`, our HTTP lib). It would be useful to see which request fails with which code/response.
It would also be helpful if the current DOM (in text form) could be shared -- probably in a private way. This would allow us to detect e.g. whether this is jiras "next gen" version or not.

We could create another ticket for that. When implemented, we may get some progress here.

What do you all think?

**Comment by tessi** [comment]
@kajatiger could you test https://github.com/bitcrowd/tickety-tick/pull/217 and see if it works for you (if you want to build the extension from git that is)? For me this change fixes the issue with new JIRA boards.

**Comment by pmeinhardt** [comment]
Hi @kajatiger, are you still experiencing this issue with the latest version?

**Comment by kajatiger** [comment]
No, actually it is fixed! Thank you for the latest version 💖

**Comment by pmeinhardt** [comment]
Sweet! Thanks a lot for your feedback @kajatiger. 💚
