### ISSUE TITLE
Fix the summary button

### ISSUE THREAD

**Issue by klappradla** [bitcrowd/tickety-tick#222]
The _summary_ button can be a helpful tool for copying the bits of text used for job logs. With the newly introduced formatting rules, the summary may contain `…` (and in general just too much text).

At best, the summary should include `[id]<title>` and concat multiple tickets via semicolon.

To make things customizable, also add a configuration option for the `summary` pattern to the options.

**Comment by klappradla** [comment]
Is it even worth tackling this @pmeinhardt with #221 going 🐎 at the moment?

**Comment by pmeinhardt** [comment]
> Is it even worth tackling this @pmeinhardt with #221 going 🐎 at the moment?

I think not. 🙂

**Comment by klappradla** [comment]
Closing this since we decided to go another path in #221 ✨
