### ISSUE TITLE
Update Mozilla and Chrome store screenshots

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#237]
Once v4 is out, we should update the Tickety-Tick screenshots in the Mozilla and Chrome store:

- https://addons.mozilla.org/en-US/firefox/addon/tickety-tick/
- https://chrome.google.com/webstore/detail/tickety-tick/ciakolhgmfijpjbpcofoalfjiladihbg

— as per https://github.com/bitcrowd/tickety-tick/pull/236#pullrequestreview-404809757

**Comment by klappradla** [comment]
What's left to do here:

- [ ] update screenshots in Chrome Web Store
- [ ] update description and metadata in Chrome Web Store (hasn't been visited for some time 🕸)
- [ ] update screenshots in Mozilla Add Ons
- [ ] update description and metadata in Mozilla Add ons

**Comment by pmeinhardt** [comment]
I updated the screenshots a while back and (slightly) tweaked the descriptions (removed Pivotal from support ticket systems etc.). I'll close this for now, but feel free to take another look and re-open if further adjustments are needed.
