### ISSUE TITLE
Markdown link export feature

### ISSUE THREAD

**Issue by juffel** [bitcrowd/tickety-tick#254]
It would be really handy to export a named link for pasting into markdown with one click:

```
[ABC-123 Ticket title](https://bitcrowd.atlassian.net/browse/ABC-123)
```

**Comment by klappradla** [comment]
I think dealing with the platform (Github, Gitlab, etc.) is beyond the scope of the extension. It's conceptualized as a link between your issue tracker and `git` as the CLI tool. So adding new buttons to extend the scope could weaken the idea of the extension.

For now, what works really well: add a link with that format to your template (e.g. for the commit message subject). Most platforms (Github especially with it's `gh` CLI) will automatically pre-fill your PR description with the contents of your commit messages. Does that fix the problem for you? If not, feel free to re-open with a suggestion on how this could look like in the browser extension 💌
