### ISSUE TITLE
Check whether we can further reduce required permissions

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#269]
Publishing on the Chrome web store, I received this hint:

![notification](https://user-images.githubusercontent.com/706519/89761169-5e1fee80-dadd-11ea-9c17-1d1b9f923c97.png)

Let's check whether we can further restrict the permissions we currently request in the `manifest.json`.

**Comment by klappradla** [comment]
`activeTab` instead of the current `tabs` sounds promising 👀
