### ISSUE TITLE
It can't find tickets on github

### ISSUE THREAD

**Issue by tessi** [bitcrowd/tickety-tick#27]
I've updated to the latest available tickety-tick version (=1.0.2) recently via the chrome extension store. Since then it does not find github issues.

I'm not sure if it is the:
* tickety update or
* the new github issues

I'm running Chrome Version 52.0.2743.116 (64-bit) on an up-to-date MacOS.

Since I'm not familiar with tickety-tick (nor react, nor chrome extensions), can you give me some pointers on how to debug this issue?

**Comment by tessi** [comment]
Ok, I'm not sure what happened (maybe it was a page reload missing?), but now it finds the ticket on a ticket's show-page. The github issues page (where we have a list of many tickets) still does not show tickets in tickety-tick.

**Comment by bitboxer** [comment]
Strangely it works on my chrome, but not on my firefox. Something is odd here.

**Comment by bitboxer** [comment]
@pmeinhardt to the rescue 👍

**Comment by pmeinhardt** [comment]
Hey @tessi, thanks for reporting this.

I quickly checked with Chrome 53.0.2785.116 (64-bit) (which I had already installed) and the show pages work as expected for me (maybe you can come grab me when you find the time to look into this on your machine).

On the issues index page (list) you'll need to select the issues you'd like to show up. This is so it's consistent with the behaviour in Pivotal for instance, where the extension will only pick up 1. selected, then (xor) 2. opened tickets (same behavior as in 0.1.4). Again, maybe come grab me when you have time so we can take look together.

**Comment by tessi** [comment]
@pmeinhardt thanks for coming over. consider my issue as closed (i'm not sure what bodo reported, so i'll leave this open for now).

**Comment by bitboxer** [comment]
I reinstalled the plugin on my firefox, now it works. Closing this one.
