### ISSUE TITLE
Try and publish for new Safari

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#275]
Apparently Apple is finally bringing the standardized WebExtensions API to Safari, which means Safari users should be able to use Tickety-Tick (without us creating a special Safari App Extension implementation). 🙌 

From the Apple macOS Big Sur feature overview:

<img src="https://user-images.githubusercontent.com/706519/99594504-2b926580-29eb-11eb-863b-d5fbd069c3ba.png" width="50%" alt="screenshot">

— https://www.apple.com/macos/big-sur/features/#safari

cc @planktonic

**Comment by klappradla** [comment]
Oh, looks very promising 👀 

Some links:
- Apple's news update from where to dive into the docs: https://developer.apple.com/news/?id=kuswih5l
- Apple's docs on web extensions: https://developer.apple.com/documentation/safariservices/safari_web_extensions

Curious on how hard / easy it is to release those extensions though. Let's see 🤞

**Comment by pmeinhardt** [comment]
Notes:

1. Build the extension: `yarn build:chrome`
2. Convert for Safari: `xcrun safari-web-extension-converter dist/chrome`, as per https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari
3. In Safari's "Develop" menu, enable "Allow unsigned extensions" (https://developer.apple.com/documentation/safariservices/safari_app_extensions/building_a_safari_app_extension#2957926)
4. Choose "Run" <kbd>Cmd</kbd> + <kbd>R</kbd>
5. Enable the extension under "Preferences > Extensions"
