### ISSUE TITLE
Update terminal notification setup

### ISSUE THREAD

**Issue by klappradla** [bitcrowd/tickety-tick#337]
As it turned out in https://github.com/bitcrowd/tickety-tick/pull/336, the `webpack-build-notifier` package we're using in development isn't compatible with Apple's new M1 architecture and probably won't in the near future. See [this issue](https://github.com/RoccoC/webpack-build-notifier/issues/63) for some background on this.

How should we proceed on this:
1. Find an alternative more future-proof setup?
2. Get rid of the terminal notifications altogether?

**Comment by pmeinhardt** [comment]
I suppose one could try to conditionally disable the plugin on Apple Silicon - possibly using Node.js' [`os.arch()`](https://nodejs.org/docs/latest-v16.x/api/all.html#all_os_osarch) or [`process.arch`](https://nodejs.org/docs/latest-v16.x/api/all.html#all_process_processarch) – but at that point I'd be leaning towards removing the dependency. 🙂

**Comment by tessi** [comment]
to be honest, I have no idea what the error is about or where it's triggered. But I have an M1 mac at hand and could test whatever you want me to test :)

**Comment by klappradla** [comment]
Thanks @pmeinhardt & @tessi 💚 

I also have an M1 and could test it there. But I prefer to have the setup run quick and friction-less for anyone looking to contribute. The extra complexity and respective maintenance effort just for the sake of the build notification does not feel worth the effort to me. The time would be better spend speeding up the build itself 😉 

Therefore going with simply removing the notifier 🧹
