### ISSUE TITLE
CLI command to generate commit message from branch name

### ISSUE THREAD

**Issue by PragTob** [bitcrowd/tickety-tick#34]
When working with tickety-tick and I want to commit my changes I have to break out of my working context (IDE + console), go to the issue tracker, and click 2 times.

What could be a better solution (imo) would be that there was a CLI command to create a commit message from the branch name (all necessary informaion should be there).

e.g. 

```
tobi@airship ~/projects/cool $ git status
On branch feature/foo-5264-implement-cool-stuff
nothing to commit, working directory clean
tobi@airship ~/projects/cool $ tt-commit
tt-commit: command not found
tobi@airship ~/projects/cool $ # makes the commit and now I can ammend it or even better it opens my editor with the commit message prefilled
```

no idea if there should be some gem/npm package to install or just a bash snippet in the readme so that one can set up a custom alias/command.

Would improve the workflow imo :)

**Comment by bitboxer** [comment]
I also thought of this, but it will be a bit harder to implement. Basically we need to store the original story name somewhere with its id to make this possible. We can't calculate that back from the branch name. Alternatively we need to ask the api of the ticket system for this information.

Sadly we can't communicate from the command line with the extension running in the browser (well, with the old firefox style plugins this was possible, but mozilla will deprecate that soonish).

So if anyone has an idea how to implement this, I am all up for this.

**Comment by pmeinhardt** [comment]
One thing that comes to mind is: https://github.com/nvie/gitflow

While this creates feature/bug/chore… branches, it - however - does not integrate with any ticket tracking system (plus it's been inactive for 4 years now).

For this to work, you'd really need a per-project (git) config containing a tracker specifier, project id and personal API access token:

- This one looks like it could work nicely with Pivotal projects at least: https://github.com/nebhale/git-pivotal-tracker-integration
- Then, there's also: https://github.com/trydionel/git-pivotal
- Maybe there are more integrations for other tracking systems but I am not aware of any git CLI tool that can handle a good range of ticket/story tracking systems

**Comment by pmeinhardt** [comment]
**A crazy thought**: How about building a ticket tracking extension into git? So that when you check out a repo, at the same time you check out issues/tickets… and they're updated/synchronized with your peers whenever you pull/push. I'll need to think about this a little.

**Comment by andreasknoepfle** [comment]
can't we just assure, that we only generate commit/branch -names that can be inferred from each other ? like this a simple tool without any api could do the job :)

**Comment by pmeinhardt** [comment]
How about: The browser extension lets you copy just the story details as some value that's easy to copy paste (e.g. JSON encoded as hex), and then you have a tick command for creating the branch from that and the commit.

To illustrate:

Assume a story that the browser extension extracts as:

```json
{ "id": "123", "type": "feature", "title": "add support for cli command" }
```

when you copy it from the extension (extra button?), you copy this:

```
7b20226964223a2022313233222c202274797065223a202266656174757265222c20227469746c65223a202261646420737570706f727420666f7220636c6920636f6d6d616e6422207d
```

which you pass to…

```shell
tick branch 7b2022696… # => git checkout -b feature/123-add-support-for-cli-command && cat … > .git/TICK_COMMIT_MESSAGE
```

and also prepares a commit message (`.git/TICK_COMMIT_MESSAGE`) which you can use via:

```shell
tick commit # => git commit -m $(cat .git/TICK_COMMIT_MESSAGE) -e
```

Just brainstorming/drafting…

**Comment by bitboxer** [comment]
Yes, that could work. And I am pretty sure with a bit of compression foo we can get the code even shorter.

**Comment by pmeinhardt** [comment]
Iterating… Could be slightly nicer if the extension button would just let you copy the complete branching command like this:

```shell
tick branch feature/123-add-support-for-cli-command -m '[#123] add support for cli command'
```

…so that you can immediately paste and run it from your terminal.

**Comment by bitboxer** [comment]
Yes, that totally makes sense to me. @PragTob what do you think?

**Comment by tessi** [comment]
Given that the usual github-workflow allows us to squash commits before merging, I have another crazy idea, which allows us to set-and-forget the branch name and commit message without writing a CLI tool.

We could have a special button which copies the following two commands:

```
git checkout -b feature/123-branch-name
git commit --allow-empty -m"generated commit message"
```

Pasting this in a terminal would create the feature branch (given we started at `master`, or wherever we wanted to branch off) and create an empty commit with the desired message.
The programmer can then start her work by adding individually-named commits on top of the empty-commit. As in the following picture of a sample branch:

![screen shot 2016-10-04 at 10 20 26](https://cloud.githubusercontent.com/assets/206108/19067146/08e07f76-8a1d-11e6-93dd-b2c87ad35222.png)

Later, in the pull request, the PR could be merged with github's merge-and-squash feature (as most of us do already).

---

Cons:

* there is an empty commit which stores the commit message of the feature

Pro:

* we do not need to implement a CLI tool
* this solution is straightforward to follow and easy to maintain
* debugging this should be easy, since the state (the empty commit) is not hidden from the user

**Comment by bitboxer** [comment]
This is a really simple solution to the problem. @pmeinhardt what do you think?

**Comment by pmeinhardt** [comment]
Yep, absolutely. I love how the solution got more and more simple over the various iterations and I think @tessi's solution is really great! 🤘🤘

The two commands should probably be joined with `&&`, so it is a single line that gets copy-pasted and users "commit" these commands by hitting enter (as opposed to copy-pasting two lines which would cause the first one to be run immediately). But that's probably what @tessi had in mind anyway.

It is probably a good idea to…

- [ ] say a word or two about this in the README:
  - assumes you're using git
  - assumes a certain workflow with squashing (unless you're okay with empty commits that is)
- [ ] think about the UI
  - third button? then maybe we should make the popover a little wider
  - what kind of icon? [terminal icon](https://octicons.github.com/icon/terminal/) would fit
  - maybe use a [button group](http://v4-alpha.getbootstrap.com/components/button-group/) for
    1. the branch name and commit message buttons, or
    2. group all buttons together

**Comment by tessi** [comment]
👍  for pauls comment. In addidtion to that we probably want to escape certain characters (e.g. `"` in the generated commit message, whitespace in the branch name, exclamation marks, ...)

**Comment by pmeinhardt** [comment]
Closing, see PR #36.
