### ISSUE TITLE
List github-project tickets

### ISSUE THREAD

**Issue by tessi** [bitcrowd/tickety-tick#35]
Github recently introduced a project (canban-borad) feature. On the project page, I'd like to use tickety-tick too.

As far as I know, it is not possible to select a single ticket. But a ticket list should be available.

<img width="1038" alt="screen shot 2016-10-03 at 18 14 56" src="https://cloud.githubusercontent.com/assets/206108/19044607/57cb706a-8995-11e6-99ce-a768a3b250b9.png">

For example in the screenshot above, I'd like to copy my branch-name/commit-message for ticket "#212 Link from offer to order"

**Comment by weiland** [comment]
I think we have to display all tickets from all lists for this.

**Comment by andreasknoepfle** [comment]
done in #63
