### ISSUE TITLE
expose notion page url 

### ISSUE THREAD

**Issue by bitboxer** [bitcrowd/tickety-tick#362]
The notion ticket id is a sad guid. I would love to be able to write a template that creates a markdown link to the ticket. Sadly the url is not available in the template.

**Comment by klappradla** [comment]
Nice to know someone is using the notion adapter 🤗 

I don't remember why I did not include the URL back then - maybe the templates weren't as sophisticated as they're now and we did not update the adapter to fit it.

Feel free to open a PR with the update if you need it right away @bitboxer. It will take a bit of time until I come around to do it myself. But it's definitely something to be done 👍
