### ISSUE TITLE
Change branch naming scheme to "#{title}-#{number}"

### ISSUE THREAD

**Issue by PragTob** [bitcrowd/tickety-tick#4]
It'd be great if we could change the naming scheme for branches to be `feature/some-title-i-can-remember-1337` so that auto complete features of the non "oh my zsh" users can be used to auto complete branch names. 

I.e. I can often remember ticket names I'm working on/guess them but never the ticket number :)

I think @pmeinhardt also was in favor of this change.

Thanks!
Tobi

**Comment by bitboxer** [comment]
Discussed this with chris. We are against chainging this just for the autocomplete. You should install `fzf` to checkout a branch instead. That helps you with your autocomplete issue :wink:

**Comment by pmeinhardt** [comment]
Noooo… :disappointed:
