### ISSUE TITLE
Commit Message Format does not lowercase

### ISSUE THREAD

**Issue by 0x6a68** [bitcrowd/tickety-tick#400]
Hi, I am not 100% sure if this is on purpose, but I would like to use `{type | lowercase}` in the commit message format. 

![2024-02-20_12-08](https://github.com/bitcrowd/tickety-tick/assets/21410/bbe226c1-9e01-40b3-94d5-d78124586f2d)

**Comment by pmeinhardt** [comment]
If you use the "auto-format" option, this will essentially "post-process" the output for the commit message and will capitalize your previously lowercased `type`.

![](https://github.com/bitcrowd/tickety-tick/blob/main/screenshots/firefox-preferences.png?raw=true)

In particular, the flow is: ticket info -> apply commit message format -> apply auto-formatting (if enabled).

Hope this helps. ✌️
