### ISSUE TITLE
Tickety is 'having' "problems" with correctly escaping 'quotes'

### ISSUE THREAD

**Issue by tessi** [bitcrowd/tickety-tick#44]
When using the new shell-command button, tickety does not correctly escape quotes. For example, the shell command for this issue is:

```
git checkout -b 'feature/44-tickety-is-having-problems-with-correctly-escaping-quotes' && git commit --allow-empty -m '[#44] Tickety is '\''having' "problems" with correctly escaping 'quotes''
```

Only the first `'` is escaped.

The expected (commit-part of the) command is:
```
git commit --allow-empty -m '[#44] Tickety is '\''having'\'' "problems" with correctly escaping '\''quotes'\'''
```

**Comment by bitboxer** [comment]
@tessi can you add the correct escaping ? That way our lovely js people can write a testcase for this and have a nice exaple

**Comment by tessi** [comment]
sure, i've updated the description accordingly
