### ISSUE TITLE
New Firefox release?

### ISSUE THREAD

**Issue by PragTob** [bitcrowd/tickety-tick#50]
The firefox release is still [version 0.1.4](https://addons.mozilla.org/de/firefox/addon/tickety-tick/) and not the new fancy versions, which starts to get problematic as part of the branch name generation seems to have changed (the branch in newer versions seems to contain capital letters, while mine only has lower case letters) :)

Thanks!

**Comment by bitboxer** [comment]
I tried several times last year to send this version to firefox, but the review process is really bad. A review said that we sent in the wrong code for a different plugin and then other reviewers irgnored the readme and tried to create the packaged version themself from the repository....I basically stopped trying. And I am a firefox user myself 😭

**Comment by bitboxer** [comment]
But if you want, you can go forward and try your luck with it.

**Comment by pmeinhardt** [comment]
We need to fix this! The amazing @andreasknoepfle has agreed to look into it next week 🎊

**Comment by PragTob** [comment]
Also seems like firefox has changed the way they want addons to be built (again!) and so ticketytick will [stop working with Firefox 57/November this year](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct)

![selection_089](https://user-images.githubusercontent.com/606517/31341595-41743740-ad0a-11e7-8ad6-267aee5624d7.png)

**Comment by bitboxer** [comment]
@PragTob luckily this is already using the new web extension api.

**Comment by andreasknoepfle** [comment]
https://addons.mozilla.org/de/firefox/addon/tickety-tick/
🎈 🎉  1.2.2 is here

**Comment by pmeinhardt** [comment]
Whoop, whoop! 🎆

**Comment by PragTob** [comment]
Thanks :tada:

**Comment by bitboxer** [comment]
![](https://media.giphy.com/media/QbkL9WuorOlgI/giphy.gif)
