### ISSUE TITLE
Copying issue name while name in selection mode works unexpected

### ISSUE THREAD

**Issue by Empty2k12** [bitcrowd/tickety-tick#53]
When copying the Issue Name while the title is being edited in Jira adds unnecessary whitespace and "SaveCanel", which I believe is because the HTML used to scrape now contains two buttons which are scraped as well.

TL;DR:
Clicking the "Commit message" button while Jira looks like this
![screen shot 2017-08-14 at 11 46 41](https://user-images.githubusercontent.com/6954968/29266947-dc934fd6-80e6-11e7-963c-6bdbcd84d63f.png)
yields the following commit message
```
[#BUG-XXX] Remove @dimen values
                                    
    SaveCancel
```

**Comment by tessi** [comment]
I can confirm this, a "fun" bug.

**Comment by tessi** [comment]
We could fix this by changing the jira-adapter at [this line](https://github.com/bitcrowd/tickety-tick/blob/101c69e79650461c87144200d7bf27c1ff0b51f3/src/common/adapters/jira.js#L22).

I guess it needs another if checking for the being-edited case.

**Comment by pmeinhardt** [comment]
Hey, I'm not currently working with JIRA. Bonus points for anyone who submits a PR @Empty2k12 🍪

**Comment by Empty2k12** [comment]
@pmeinhardt I tried setting up a dev environment a couple weeks ago for another feature I would have liked to be implementd but the first `yarn` step failed me... When I have nothing to do sometime I can try to get it running again.

**Comment by pmeinhardt** [comment]
You mean the `yarn install` step @Empty2k12? Mmh. I could imagine [`node-sass`](https://github.com/sass/node-sass) being a problem because it's building a native (node) extension on install. But that's a plain guess. If you can provide some details, e.g. error output, from the failing command maybe we can help solve these and get you up and running 😀

**Comment by Empty2k12** [comment]
I got the setup running, will take a look at this issue and my other idea soon.

**Comment by tessi** [comment]
Hey Geo, cool that you've got the setup right. In the meantime i've put a PR online ( #56 ) which should fix this issue. A review would be nice :)


Regarding the other feature you have in mind: It would be nice if you could open an issue with your feature idea first. This way we're able to give you early feedback, discuss any blockers or cheer for you 🎉
