### ISSUE TITLE
Make PR name configurable

### ISSUE THREAD

**Issue by Empty2k12** [bitcrowd/tickety-tick#59]
# Problem
Currently tickety-tick generates PR names with the following structure 

`[#1337] Localise to L33T language`.

this works fine when working with JIRA, but is suboptimal when working with GitHub because a `Closes #1337` has to be added manually to the PR body. Luckily, GitHub supports PR titles like this

`Localise to L33T language (Closes #1337)`

# Solution
**Make tickety-tick's string formatting configurable**

# Further considerations
 * Preferably the PR would add a settings page that can later be extended with other settings
 * There could be two predefined ways to format the string, selectable via :
     * Normal Format: `[#1337] Localise to L33T language`
     * GitHub Format: `Localise to L33T language (Closes #1337)`
 * Additionally there could be a textarea to write out custom formatting rules with available variables (`number` and `title`): `#{number}: #{title} (Any other text can go here, too)`

# Mockup
![img_20171009_113903](https://user-images.githubusercontent.com/6954968/31332487-e31768c0-ace6-11e7-9fa9-bd25910ea98e.jpg)
Please excuse my shitty paper sketch, my Sketch demo license ran out and I am too poor to buy one.

**Comment by tessi** [comment]
In my opinion this is a good idea 🎉 
Please keep in mind, that tickety-tick targets multi-browser support (chrome, firefox, opera, safari if i'm not mistaken). So whatever settings you build, it needs to work on all mayor browsers :)

**Comment by pmeinhardt** [comment]
Tickety-Tick 2.0 just landed in the official Firefox and Chrome stores, featuring configurable commit messages, branch names and commands :gift:
