### ISSUE TITLE
Support auto-updating

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#6]
Hey, installed Tickety Tick as a Chrome/Chromium Extension and just found out it's not automatically updated. I had to manually uninstall the old and install the new version.

Maybe we could enable auto-updating?

Infos for Chrome: https://developer.chrome.com/extensions/autoupdate

Cheers

**Comment by bitboxer** [comment]
That is strange, it should have done so, quoting the site you linked:

> If you publish using the Chrome Developer Dashboard, you can ignore this page. 

:cry:

**Comment by pmeinhardt** [comment]
Huh? Could it be me using Chromium and not Google Chrome then?

**Comment by bitboxer** [comment]
Will close this now. If it happens again, we need to investigate.
