### ISSUE TITLE
Release 1.2.2 in all stores

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#69]
- [x] Mozilla Addon
- [x] Chrome extension
- [ ] Opera

**Comment by andreasknoepfle** [comment]
![screen shot 2017-11-15 at 10 40 52](https://user-images.githubusercontent.com/239398/32829163-8b7bccd2-c9f1-11e7-9537-8b27260191ad.png)

Today is a good day! Big thanks to @bitboxer for making this possible :)

**Comment by bitboxer** [comment]
![Party!!](https://media.giphy.com/media/3KC2jD2QcBOSc/giphy.gif)

**Comment by pmeinhardt** [comment]
@andreasknoepfle how do we go about publishing the opera release? Should we tackle this on our next infrastructure day?

**Comment by andreasknoepfle** [comment]
Already waiting on moderation:
![screen shot 2017-11-20 at 10 26 27](https://user-images.githubusercontent.com/239398/33011140-4f372876-cddd-11e7-8988-91d8487a71f3.png)

**Comment by andreasknoepfle** [comment]
Still awaiting moderation. Dunno if they will do it ever :(
