### ISSUE TITLE
Make branch name configurable

### ISSUE THREAD

**Issue by bitboxer** [bitcrowd/tickety-tick#70]
I have a build system that can't deal with `/` in the branch name and would love to be able to configure the branch name. For our purpose it would be awesome if it can be changed to `feature-1234-awesome-refactoring`.

![](https://media.giphy.com/media/aZ4sQUpybai5y/giphy.gif)

**Comment by andreasknoepfle** [comment]
Seems to me could go into a similar direction as #59

**Comment by bitboxer** [comment]
Yes.

**Comment by pmeinhardt** [comment]
Tickety-Tick 2.0 just landed in the official Firefox and Chrome stores, featuring configurable commit messages, branch names and commands :gift:

**Comment by bitboxer** [comment]
Thank you!!!!

![](https://media.giphy.com/media/tjuWJTevYz1Oo/giphy.gif)
