### ISSUE TITLE
Changed defaults for 2.0.0

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#88]
Seems like the default format changed in 2.0.0 since we used to uppercase the Ticket IDs in the branchname. Not anymore sadly.

**Comment by klappradla** [comment]
I also realized that - thought it was on purpose though 🙈

**Comment by andreasknoepfle** [comment]
Don't know. Could also very well be on purpose :-) maybe we need to ask @pmeinhardt

**Comment by pmeinhardt** [comment]
Ah, I don't think they were explicitly upcase'd but just inserted as they were. For instance if you have a ticket ID like "RC-1" from Jira, it would just use that. To be honest I would need to look that up though. If it's a problem, feel free to open a PR :wink: 

On the other hand, for me personally, having branchnames all lowercase seems a bit nicer. But I am completely open for suggestions and it was not an explicit goal of the new release to change that.

**Comment by klappradla** [comment]
The 🗯 thing is still all uppercase though. Makes sense have both aligned I'd say. Just realized it when using Jira. People may have set up additional automated workflows that depend on the correct naming. But let's see if someone even realized 💥

**Comment by pmeinhardt** [comment]
To me, the branch name is somewhat different from the message:
For the branch name, I feel like slugified/lowercased makes more sense (it needs to be usable on the command-line), whereas it's fine to use the ID as it comes from the ticket system (any casing) in the commit message.

But that is my personal taste only!

To further illustrate: for Trello we get numbers as ticket IDs so casing doesn't matter, Jira usually has uppercase letters plus dash plus number.

Here are the current defaults for reference:

https://github.com/bitcrowd/tickety-tick/blob/a612e07ec28650521cfaa969cd6026cab6b9f46b/src/common/format.js#L6-L10

But like I said, if you need it to be different, there are two options:

1. explicitly configure it (if you think the new default is fine "as a default") in which case we can close this issue
2. open a PR to change the defaults if it's really a problem for you

:slightly_smiling_face: :wave:

**Comment by andreasknoepfle** [comment]
`herodot`s linking also needs to be reconfigured when this changes (i noticed) 

We will have some hickup time while switching i fear.
For anyone who needs the old behaviour the config for the branch name needs to be 
```
{type}/{id | slugify | uppercase}-{title |slugify}
```
