### ISSUE TITLE
No tickets found on JIRA backlog view

### ISSUE THREAD

**Issue by lwassermann** [bitcrowd/tickety-tick#90]
TT finds no issues on the JIRA backlog view, not even if a single item is selected (see #28 for more discussions if none are selected). This might be cause by a recent overhaul of the JIRA UI.

The `Active Sprints` view still works as desired.

**Comment by pmeinhardt** [comment]
If you want to @lwassermann, we could pair on this 😉 I think I'll have a little time today/this week.

**Comment by tessi** [comment]
should be clode by #92
