### ISSUE TITLE
Enhance commit messages

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#93]
Thanks to some inspiration from @klappradla, I would like to propose working on the following improvements:

1. [x] Extend ticket objects (currently `id`, `type`, `title`, `fmt`) by adding `description` and `url` if available
2. [x] Format commit messages with a 50 char title, empty line, commit description with a text width of 72 chars — https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

If you have additional ideas regarding better commit messages, let's gather them here 🙂 

cc @tessi, @maltoe

**Comment by tessi** [comment]
A link, if possible to the original ticket would be great.

**Comment by pmeinhardt** [comment]
Just two quick notes for future selves 💭

1. **Adding ticket URLs**

    My first thought was: Easy! We already pass the document location as an argument to the adapters.

    On second thought: The scanner probably needs to add the URL on a case-by-case basis. Consider the GitHub issues list for instance, where you can select multiple issues via their checkboxes. The ticket URLs shouldn't be `https://github.com/<orga>/<repo>/issues` but `…/issues/<id>`.

2. **Commit message formatting**

    I have been thinking about how to properly format commit messages (wrap title after 50 chars, text after 72 chars, with proper alignment/indents…) and prettier's markdown support could make it a valid option (for most of this):

    https://is.gd/DVf7Jt 💅 (uses `--text-width 72`, `--prose-wrap always`)

    I'll keep an eye out for more lightweight alternatives though 👀

**Comment by pmeinhardt** [comment]
The auto-formatting is done. While a few adapters already return the ticket URL etc., most of them don't. While this additional information is optional, these adapters should still be updated ✌️
