### ISSUE TITLE
Fix icon loading on about view

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#97]
The Tickety-Tick icon on the about view seems to not be loading at the moment (in all supported browsers). The code for that does not seem to have changed in a long time so I wonder what is causing this issue.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/706519/47253677-01ee6500-d446-11e8-9ea5-26ab5113bf9f.png">

**Comment by pmeinhardt** [comment]
🤦‍♂️ … the icons are currently copied using the `copy-webpack-plugin` using `{ flatten: true }`.

The path used in the DOM node rendered by the component does not match the build output.

**Comment by tessi** [comment]
This should be fixed now thanks to @pmeinhardt
